<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Post extends Model
{
    use HasFactory;

    // Mass assignment of Post fields (mass assignment vulnerability)
    protected $fillable = ['title', 'excerpt', 'body', 'slug', 'category_id'];
//    protected $guarded = ['id']; // empty array will stop mass assignment

//    // Archaic way of doing route model binding on an active record field that isn't the id
//    public function getRouteKeyName()
//    {
//        return 'slug'; // TODO: Change the autogenerated stub
//    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}
